#!/bin/bash

VER=1.4.0
DAT=25.04.2012
TIME=`date`

TMP_DIR=/tmp/knowhowERP
mkdir -p $TMP_DIR

F18_INSTALL_ROOT=/opt/knowhowERP

GCODE_URL_ROOT_F18=http://knowhow-erp-f18.googlecode.com/files
GCODE_URL_ROOT=http://knowhow-erp.googlecode.com/files

LOG_F=$TMP_DIR/F18_update.log

WHOAMI=`whoami`
USER="bringout"

SERVICE='F18'
ARCH=`uname -m`

if [[ "$USER" == "root" ]]; then
   OWNER=$SUDO_USER
else
   OWNER=$USER
fi




DOWNLOAD_DIR=~/Downloads
mkdir -p $DOWNLOAD_DIR

ans=$(zenity --list \
    --text "Odaberite operaciju koju želite uraditi: " \
    --checklist \
    --column "Označi" \
    --column "Operacija" \
    --column "Opis" \
    TRUE "update" "F18 update" \
    FALSE "template" "Instalacija/update predložaka" \
    --separator=":" \
    --width 450 --height 200 ); 
#echo $ans

if [[ "$ans" =~ "update" && "$ans" != "" ]]; then
    if ps ax | grep -v grep | grep -w $SERVICE > /dev/null
    then
	zenity --error --title="Greška!" --text="Da bi ste izvršili nadogradnju morate zatvoriti $SERVICE!"
	exit 0
    fi
#Provjeri da li je skriptu pokrenuo korisnik bringout
    if [ "$WHOAMI" != "$USER" ]; then
	zenity --error --title="Greška!" --text="Morate biti logovani kao korisnik: $USER"
	exit 0
    fi

    cd $DOWNLOAD_DIR
    F18_VER=$(zenity --entry \
	--title="Unos verzije za update" \
	--text="Unesite verziju F18 na koju želite nadograditi:" \
	--entry-text="1.0.");

    #ako je korisnik odustao od downloada, prekini izvršenje skripte
    if [ $? -eq 1 ]; then
	exit 0
    fi

    D_FILE=F18_Ubuntu_${ARCH}_${F18_VER}.gz
    #echo $D_FILE

#Download fajla
    wget "$GCODE_URL_ROOT_F18/$D_FILE" 2>&1 | sed -u 's/^.* \+\([0-9]\+%\) \+\([0-9.]\+[GMKB]\) \+\([0-9hms.]\+\).*$/\1\n# Downloading... \2 (\3)/' | zenity --progress --title='Download' --no-cancel --auto-close

    #Ukolikno download nije uspješan tj. fajl nije pronađen na trenutnoj lokaciji stavi to u log file
    if [[ ! -f $D_FILE ]]; then
	zenity --error --title="Greška!" --text="Nije pronađen fajl $D_FILE"
	echo "$TIME Fajl $D_FILE nije pronađen." >> $LOG_F
	exit 0
    fi
    #Počni update
    (
	echo "20" ; sleep 1
	echo "# Kopiram $D_FILE u privremeni direktorij..."; sleep 1
	mv -f $D_FILE $TMP_DIR

    # $? is shell variable that contains outcome of last ran command
    # cp will return 0 if there was no error
	if [ $? -eq 0 ]; then
	    echo "$TIME Kopiranje uspješno završeno" >> $LOG_F
	else
	    echo "$TIME Greška prilikom kopiranja" >> $LOG_F
	    zenity --error --title="Greška!" --text="Dogodila se pogreška prilikom kopiranja na privremenu lokaciju!"
	    exit 0
	fi

	echo "40" ; sleep 1
	echo "# Raspakujem arhivu..."; sleep 1
	cd $TMP_DIR
	FILE=F18_Ubuntu_${ARCH}_${F18_VER}
	gzip -dNf $FILE.gz
	if [ $? -eq 0 ]; then
	    echo "$TIME Fajl uspješno otpakovan" >> $LOG_F
	else
	    echo "$TIME Greška prilikom otpakivanja arhive" >> $LOG_F
	    zenity -error --title="Greška!" --text="Greška prilikom otpakivanja arhive!"
	    exit 0
	fi
	#Brišemo ovaj fajl
	rm -f $FILE.gz

	echo "70" ; sleep 1
	echo "# Vršim update F18..."; sleep 1
	FILE=$F18_INSTALL_ROOT/bin/
	mv -f F18 $FILE
	if [ $? -eq 0 ]; then
	    echo "$TIME Prebacujem F18 fajl u $F18_INSTALL_ROOT/bin/" >> $LOG_F
	else
	    echo "$TIME Greška prilikom prebacivanja fajla u $F18_INSTALL_ROOT/bin/" >> $LOG_F
	    zenity --error --title="Greška!" --text="Greška prilikom prebacivanja fajla u $F18_INSTALL_ROOT/bin/"
	    exit 0
	fi

	echo "90" ; sleep 1
	echo "# Dodjeljujem potrebne permisije "; sleep 1
	chmod +x $FILE/F18
	if [ $? -eq 0 ]; then
	    echo "$TIME Dodjeljujem permisije F18 fajlu" >> $LOG_F
	else
	    echo "$TIME Ne mogu dodijeliti permisije za $F18_INSTALL_ROOT/F18" >> $LOG_F
	    zenity --error --title="Greška!" --text="Greška prilikom dodjeljivanja izvršnih permisija $F18_INSTALL_ROOT/F18 fajlu"
	    exit 0
	fi

	echo "100" ; sleep 1
	echo "# Update je uspješno završen" ; sleep 1

    ) | zenity --progress \
	--title="F18 update" \
	--text="Započinjem update F18..." \
	--percentage=0
    if [ "$?" = -1 ]; then
	zenity --error \
	    --text="Update otkazan. Dogodila se greška."
    fi
fi
if [[ "$ans" =~ "template" && "$ans" != "" ]]; then

    cd $DOWNLOAD_DIR
    TPL_VER=$(zenity --entry \
	    --title="Unos verzije predložaka" \
	--text="Unesite verziju predložaka koju želite instalirati:" \
	--entry-text="1.");

    #U slučaju da korisnik odustane
    if [ $? -eq 1 ]; then
	exit 0
    fi

    #Provjeravam da li user ima permisije za /opt/knowhowERP direktorij
    OWNER=`ls -l /opt | grep knowhowERP | awk '{print $3}'`
    if [[ $USER != $OWNER ]]; then
	zenity --error --title="Greška!" --text="Korisnik $USER nema pristup $F18_INSTALL_ROOT folderu"
	exit 0
    fi

    if [[ $WHOAMI == $USER ]]; then

	cd $TMP_DIR
	TPL_FILE=F18_template_$TPL_VER

	(
	    echo "20" ; sleep 1
	    echo "# Downloadujem potrebe fajlove..." ; sleep 1

            #Download
	    wget $GCODE_URL_ROOT_F18/$TPL_FILE.tar.bz2 2>&1 | \
		sed -u 's/^.* \+\([0-9]\+%\) \+\([0-9.]\+[GMKB]\) \+\([0-9hms.]\+\).*$/\1\n# Downloading... \2 (\3)/' | \
		zenity --progress --title='Download' --no-cancel --auto-close

            #Ako downloadovani TPL fajl nije pronađen
	    if [[ ! -f $TPL_FILE.tar.bz2 ]]; then
		zenity --error --title="Greška!" --text="Nije pronađen fajl $TPL_FILE.tar.bz2"
		echo "$TIME Fajl $TPL_FILE.tar.bz2 nije pronađen" >> $LOG_F
		exit 0
	    fi
    
	    echo "55" ; sleep 1
	    echo "# Instaliram predloške..." ; sleep 1

	    echo "Instaliram predloške u $F18_INSTALL_ROOT/template" >> $LOG_F
	    if [ -d "$F18_INSTALL_ROOT/template" ]; then
		tar -C $F18_INSTALL_ROOT -jxf $TPL_FILE.tar.bz2 | \
		    zenity --progress --title='Otpakujem arhivu' --no-cancel --auto-close
	    else
		mkdir $F18_INSTALL_ROOT/template
		tar -C  $F18_INSTALL_ROOT -jxf $TPL_FILE.tar.bz2 | \
		    zenity --progress --title='Otpakujem arhivu' --no-cancel --auto-close
	    fi

	    echo "90" ; sleep 1
	    echo "# Uklanjam privremene fajlove..." ; sleep 1

            #uklanjam downloadovani fajl iz temp dir
	    rm -f $TMP_DIR/$TPL_FILE.tar.bz2 

	    echo "100" ; sleep 1
	    echo "# Instalacija template je uspješno završena" ; sleep 1
	) | zenity --progress \
	    --title="Instalacija predložaka" \
	    --text="Započinjem instalaciju/update predložaka..." \
	    --percentage=0

	if [ "$?" = -1 ]; then
	    zenity --error --title="Greška" \
		--text="Instalacija predložaka otkazana. Dogodila se greška."
	fi
    fi
fi