#!/bin/bash
#0.1.0
#06.12.2011 

if [[ "$1" == "" ]]; then
echo "niste unijeli verziju koju zelite postaviti, npr 0.9.5"
exit 0
fi
 
NVER=$1
SERVICE='F18'
ARCH=`uname -m`
 
if ps ax | grep -v grep | grep -w  $SERVICE > /dev/null
then
    echo "$SERVICE je pokrenut molim da ga zatvorite i ponovite update"
exit 0

else
    echo "$SERVICE nije pokrenut"
fi
 

echo -n "pricekajte u toku je download..."
wget -N http://knowhow-erp-f18.googlecode.com/files/F18_Ubuntu_"$ARCH"_"$NVER".gz

echo "ok - zavrseno"

echo "upgrade"

gzip -dN  F18_Ubuntu_"$ARCH"_"$NVER".gz

mv F18 ~/bin
chmod +x ~/bin/F18 

echo "update je zavrsen"


